site_name: Yogic English
site_url: https://yogicenglish.github.io/platform/
repo_url: https://github.com/yogicenglish/platform/

theme:
    name: material
    language: ru # The build's language

    logo: img/isha-logo.png
    favicon: img/isha-logo.png

    features:
        - navigation.tracking
        - navigation.tabs
        - content.action.edit
        - content.action.view
        - navigation.path
        - navigation.top
        - navigation.footer

    palette:
        - media: '(prefers-color-scheme: light)' # Palette toggle for light mode
          scheme: default
          primary: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        - media: '(prefers-color-scheme: dark)' # Palette toggle for dark mode
          scheme: slate
          primary: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

extra:
    social:
        - icon: simple/telegram
          link: https://t.me/IshaEnglish
          name: Telegram
#   Language Switch
#   alternate:
#       - name: Русский
#         link: /
#         lang: ru

extra_javascript:
    - js/extra.js
    - js/lite-yt-embed.js

extra_css:
    - css/exercises.css
    - css/lite-yt-embed.css

plugins:
    - search:
          lang: ru # Set language for search

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - attr_list
    - md_in_html

nav:
    - 'Главная': 'index.md'
    - 'Grammar Lessons':
          - 'lessons/present-simple.md'
          - 'lessons/present-continuous.md'
          - 'lessons/adjectives-prepositions.md'
          - 'lessons/going-to.md'
          - 'lessons/nouns.md'
          - 'lessons/past-simple.md'
          - 'lessons/listening&reading.md'
          - 'lessons/future.md'
          - 'lessons/future-simple.md'
          - 'lessons/Requests&offers.md'
          - 'lessons/Communication.md'

    - 'Бесплатные Сессии':
          - 'free-sessions/23-07-01.md'
    - 'Vocabulary':
          - 'vocabulary/feelings.md'
          - 'vocabulary/food.md'
    - 'Блог': 'https://https://ishavolru.hashnode.dev/'

copyright: Copyright &copy; 2023 Yogic English
